/**
 * Parity tests for the JS dynamics port vs cellpose.dynamics.compute_masks.
 *
 * Fixtures (generated by ~/cellpose-js-spike/gen_dynamics_fixtures.py):
 *   - single_cell_128     1 ground-truth mask
 *   - three_cells_192     up to 5 ground-truth masks (overlapping flows produce splits)
 *   - empty_96            0 masks (background only)
 *
 * Gate (plan): per-instance mean IoU ≥ 0.9 across the fixture set.
 */
import { describe, it, expect } from 'vitest';
import { readNpy } from './util/npy.js';
import { instanceIoUs } from './util/iou.js';
import { computeMasks } from '../src/postprocess/compute_masks.js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIX = path.join(__dirname, 'fixtures_dyn');

interface Case {
  name: string;
  gate: number;
}

describe('compute_masks parity', () => {
  const cases: Case[] = [
    { name: 'single_cell_128', gate: 0.9 },
    // Pre-fix this fixture sat at 0.601 because JS used Math.round on the
    // final convergence coordinates while PyTorch's `.int()` truncates. The
    // 1-pixel shift split two small overlap-zone labels off their Python
    // counterparts. After switching to Math.trunc all 5 labels match at IoU
    // 1.000, so the gate is tightened here to catch any regression.
    { name: 'three_cells_192', gate: 0.99 },
    { name: 'empty_96', gate: 0.99 },
  ];
  for (const c of cases) {
    it(c.name, () => {
      const dP = readNpy(path.join(FIX, `${c.name}_dP.npy`));
      const cp = readNpy(path.join(FIX, `${c.name}_cellprob.npy`));
      const exp = readNpy(path.join(FIX, `${c.name}_mask.npy`));
      const [, H, W] = dP.shape as [number, number, number];
      const got = computeMasks(dP.data as Float32Array, cp.data as Float32Array, H, W);
      const expArr = exp.data as Uint16Array;
      const { mean, per } = instanceIoUs(expArr, got.masks);

      console.log(
        `[${c.name}] expected=${expArr.reduce((m, v) => Math.max(m, v as number), 0)} predicted=${got.count} mean IoU=${mean.toFixed(3)} per=[${per.map((v) => v.toFixed(2)).join(', ')}]`,
      );
      expect(mean).toBeGreaterThanOrEqual(c.gate);
    });
  }
});
